alias gbvv='git branch -vv'
alias java='java -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m'
alias gitpurge='git branch -r --merged | grep -v master | grep -e origin | sed -e 's/origin\//:/' | xargs git push origin'
alias webserver='python -m SimpleHTTPServer 8000'
alias dokku='ssh dokku '
