[onepassword.secrets]
  claude_code_ssh = "op://tqfo2e4hghec2ykgmvjhk74se4/ysocytjybo3x375zjqef7qwbrm"
  github_ssh = "op://tqfo2e4hghec2ykgmvjhk74se4/cyq3npw6tlxixptgrgjiwjvkfe"
  dokploy = "op://tqfo2e4hghec2ykgmvjhk74se4/axqqhthnpc7ta2n24glhtiadsy"
