[onepassword.accounts]
  personal = "my.1password.com"
  work = "reservinc.1password.com"

[onepassword.secrets]
  claude_code_ssh = "op://tqfo2e4hghec2ykgmvjhk74se4/ysocytjybo3x375zjqef7qwbrm"
  github_ssh = "op://tqfo2e4hghec2ykgmvjhk74se4/cyq3npw6tlxixptgrgjiwjvkfe"
  dokploy = "op://tqfo2e4hghec2ykgmvjhk74se4/axqqhthnpc7ta2n24glhtiadsy"
  reserv_github_package_registry = "op://Employee/Reserv Github Package Registry/credential"
  reserv_jira_cli_token = "op://Employee/JIRA CLI Access Token/credential"

