[packages.homebrew]
  casks = [
    "1password-cli",
    "alfred",
    "caffeine",
    "claude",
    "claude-code",
    "discord",
    "docker-desktop",
#    "epic-games",
    "firefox@developer-edition",
    "font-jetbrains-mono-nerd-font",
    "ghostty",
    "google-chrome",
    "handy",
 #   "lm-studio",
 #   "lulu",
    "obsidian",
 #   "zen",
  ]
  formulae = [
    "asitop",
    "ast-grep",
    "atuin",
    "bat",
    "chezmoi",
#    "cloudflared",
    "container",
    "eza",
    "fd",
    "fzf",
    "gh",
    "git",
    "git-delta",
    "gnupg",
    "libyaml",
    "luarocks",
    "mise",
    "neovim",
#    "playwright-cli",
    "ripgrep",
    "rtk",
    "starship",
    "tmux",
    "tokei",
    "wget",
    "worktrunk",
    "yq",
    "zsh",
#    "anomalyco/tap/opencode",
#    "jundot/omlx/omlx",
    "raganw/tap/tmux-sessionizer",
  ]

